config/routes.rb
Rails.application.routes.draw do

  resources :conversations do
    resources :messages
  end

  resources :myapis
  match "product_by_category" => "myapis#product_by_category", as: :product_by_category, via: [:get, :post]
  match "product_by_id" => "myapis#product_by_id", as: :product_by_id, via: [:get, :post]
  match "all_products" => "myapis#all_products", as: :all_products, via: [:get, :post]
  match "customer_review" => "myapis#customer_review", as: :customer_review, via: [:get, :post]
  match "my_info" => "myapis#my_info", as: :my_info, via: [:get, :post]
  match "edit_my_info" => "myapis#edit_my_info", as: :edit_my_info, via: [:get, :post]
  match "my_shoppinglist" => "myapis#my_shoppinglist", as: :my_shoppinglist, via: [:get, :post]
  match "my_wish_list" => "myapis#my_wish_list", as: :my_wish_list, via: [:get, :post]
  match "my_coupon_list" => "myapis#my_coupon_list", as: :my_coupon_list, via: [:get, :post]
  match "myorder_list" => "myapis#myorder_list", as: :myorder_list, via: [:get, :post]
  match "mycancel_list" => "myapis#mycancel_list", as: :mycancel_list, via: [:get, :post]
  match "mycart_list_by_buyer_id" => "myapis#mycart_list_by_buyer_id", as: :mycart_list_by_buyer_id, via: [:get, :post]
  match "mycart_list_by_cart_key" => "myapis#mycart_list_by_cart_key", as: :mycart_list_by_cart_key, via: [:get, :post]
  post 'add_to_cart_mobi' => 'myapis#add_to_cart_mobi', as: 'add_to_cart_mobi'
  post 'add_to_cart_mobi_with_key' => 'myapis#add_to_cart_mobi_with_key', as: 'add_to_cart_mobi_with_key'
  post 'delete_cart' => 'myapis#delete_cart', as: 'delete_cart'

  resources :cover_images
  scope "(:locale)", locale: /en|mm/ do
  resources :currency_exchanges
  resources :wish_lists
  resources :request_products
  get 'thanks_for_request' => 'request_products#thanks_for_request', as: 'thanks_for_request'

  devise_for :buyers, :controllers => {:sessions => "buyers/sessions", :registrations => "buyers/registrations"}

  namespace :myapi do
    namespace :v1 do
      devise_scope :buyer do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        post 'buyer_new' => 'registrations#buyer_new', :as => 'buyer_new'
        get 'my_sign_out' => 'sessions#destroy', :as => 'logout'
        
      end
    end
  end

  devise_for :admins, :controllers => {:sessions => "admins/sessions", :registrations => "admins/registrations"}
  resources :admins
  get 'dashboard' => 'admins#dashboard'
  get 'buyer_list' => 'admins#buyer_list'
  get 'other_request_products' => 'admins#other_request_products'  

  resources :comments
  resources :coupons
  resources :buyers
  resources :carts

  resources :line_items
  get 'cart_item' => 'line_items#cart_item', as: 'cart_item'

  resources :orders

   match "order_complete" => "orders#order_complete", as: :order_complete, via: [:get, :post]

  resources :frontends
  get 'submit_online_payment_mobi' => 'frontends#submit_online_payment_mobi'  

  root 'frontends#home'
 
  match 'fill_your_order_form/:id' => 'frontends#fill_your_order_form', as: 'fill_your_order_form', via: [:get, :post]
  get 'submit_online_payment' => 'frontends#submit_online_payment', as: 'submit_online_payment', via: [:get, :post]

  get 'order_form' => 'frontends#order_form', as: 'order_form'
  get 'about_us' => 'frontends#about_us'
  match 'contact_us' => 'frontends#contact_us', as: :contact_us, via: [:get, :post]
  get 'help' => 'frontends#help'
  get 'product_info/:id' => 'frontends#product_info', as: 'product_info'
  get 'view_image/:id' => 'frontends#view_image', as: 'view_image'

  get 'search_result' => 'frontends#search_result'

  
   get 'how_to_buy' => 'frontends#how_to_buy'
   get 'payment' => 'frontends#payment'
   get 'shipment_delivery'  => 'frontends#shipment_delivery'
   get 'customer_feedback'  => 'frontends#customer_feedback'

   get 'career_opportunity'  => 'frontends#career_opportunity'
   get 'termns_and_condition'  => 'frontends#termns_and_condition'
   get 'privacy_policy'  => 'frontends#privacy_policy'

   get 'my_account'  => 'frontends#my_account'

   get 'check_out'  => 'frontends#check_out'
   
   get 'use_coupon'  => 'frontends#use_coupon'
   post 'add_to_wish_list'  => 'frontends#add_to_wish_list'

  get 'product_detail_mobiview/:id'  => 'frontends#product_detail_mobiview'
  
  get 'customer_review_mobiview/:id'  => 'frontends#customer_review_mobiview'

  get 'productqanda_mobiview/:id'  => 'frontends#productqanda_mobiview'

  get 'notice_mobiview/:id'  => 'frontends#notice_mobiview'

  get 'my_wishlist'  => 'frontends#my_wishlist'

  get 'my_coupon'  => 'frontends#my_coupon'

  get 'send_to_order'  => 'frontends#send_to_order'

  get 'use_mpu' => 'frontends#use_mpu'

  get 'use_cash_deposit' => 'frontends#use_cash_deposit'

  get 'use_bank_transfer' => 'frontends#use_bank_transfer'

  get 'my_order_list' => 'frontends#my_order_list'

  get 'my_shopping_list' => 'frontends#my_shopping_list'

  get 'my_order_detail/:id' => 'frontends#my_order_detail', as: 'my_order_detail'
  

  get 'cancel_order/:id' => 'frontends#cancel_order', as: 'cancel_order'
  
  get 'my_cancel_list' => 'frontends#my_cancel_list'

  get 'my_personal_info/:id' => 'frontends#my_personal_info', as: 'my_personal_info'

  get 'product_list' => 'frontends#product_list', as: 'product_list'

  get 'pc_version' => 'frontends#pc_version', as: 'pc_version'

  get "send_to_pusher" => "frontends#send_to_pusher", :as => :send_to_pusher
  get 'chat_with' => 'frontends#chat_with', :as => :chat_with

  get 'chat_to_seller' => "frontends#chat_to_seller", :as => :chat_to_seller

  
  resources :products

      end
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/buyer_list.html.erb
<div class="panel panel-default">
  <div class="panel-body">
      <div class="col-md-12">
    <h3>Buyers
    </h3><hr/>

		<table class="table">
		  <thead>
		    <tr>
		      <th>Buyer name</th>
		      <th>Buyer phone</th>
		      <th>Buyer email</th>
		      <th>Buyer township</th>
		      <th>Buyer address</th>
		      <th colspan="2"></th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @buyers.each do |buyer| %>
		      <tr>
		        <td><%= buyer.buyer_name %></td>
		        <td><%= buyer.buyer_phone %></td>
		        <td><%= buyer.email %></td>
		        <td><%= buyer.buyer_township %></td>
		        <td><%= buyer.buyer_address %></td>
		        <td><%= link_to 'Edit', edit_buyer_path(buyer) %></td>
		        <td><%= link_to 'Destroy', buyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
		<%= will_paginate @buyers, renderer: BootstrapPagination::Rails %>

    <br>
    </div>

   

    </div>
</div>

app/views/admins/dashboard.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <h3>Products</h3><hr/>
    <%= link_to 'Product listing', products_path %>
     <%= @products %>
  </div>
</div>



<div class="panel panel-default">
  <div class="panel-body">
      <h3>Orders </h3><hr/>
    <%= link_to 'Order listing', orders_path %>
     <%= @orders %>
  </div>
</div>



<div class="panel panel-default">
  <div class="panel-body">
    <h3>Coupons </h3><hr/>
    <%= link_to 'Cuopon listing', coupons_path %>
    <%= @coupons %>
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-body">
    <h3>Currency exchange rate </h3><hr/>
    <%= link_to 'Currency Exchange rate', currency_exchanges_path %>
    <%= @currency_exchanges %>
  </div>
</div>




<div class="panel panel-default">
  <div class="panel-body">
    <h3> Messages </h3><hr/>
    <%= link_to 'Currency Exchange rate', currency_exchanges_path %>
    <%= @currency_exchanges %>
  </div>
</div>

app/views/admins/other_request_products.html.erb
<div class="panel panel-default">
  <div class="panel-body">
      <div class="col-md-12">
    <h3>Requested Products
    </h3><hr/>

		<table class="table">
		  <thead>
		    <tr>
		      <th>Title</th>
		      <th>Sender Name</th>
		      <th>Sender Phone</th>
		      <th>Sender Email</th>
		      <th colspan="2"></th>
		    </tr>
		  </thead>

		  <tbody>
    		<% @request_products.each do |request_product| %>
		      <tr>
		        <td><%= request_product.title %></td>
		        <td><%= request_product.sender_name %></td>
		        <td><%= request_product.sender_phone %></td>
		        <td><%= request_product.sender_email %></td>
		      
		        <td><%= link_to 'Show', request_product %></td>
		        <td><%= link_to 'Destroy', request_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>

    <br>
    </div>

   

    </div>
</div>