config/routes.rb
Rails.application.routes.draw do

  resources :conversations do
    resources :messages
  end

  resources :myapis
  match "product_by_category" => "myapis#product_by_category", as: :product_by_category, via: [:get, :post]
  match "product_by_id" => "myapis#product_by_id", as: :product_by_id, via: [:get, :post]
  match "all_products" => "myapis#all_products", as: :all_products, via: [:get, :post]
  match "customer_review" => "myapis#customer_review", as: :customer_review, via: [:get, :post]
  match "my_info" => "myapis#my_info", as: :my_info, via: [:get, :post]
  match "edit_my_info" => "myapis#edit_my_info", as: :edit_my_info, via: [:get, :post]
  match "my_shoppinglist" => "myapis#my_shoppinglist", as: :my_shoppinglist, via: [:get, :post]
  match "my_wish_list" => "myapis#my_wish_list", as: :my_wish_list, via: [:get, :post]
  match "my_coupon_list" => "myapis#my_coupon_list", as: :my_coupon_list, via: [:get, :post]
  match "myorder_list" => "myapis#myorder_list", as: :myorder_list, via: [:get, :post]
  match "mycancel_list" => "myapis#mycancel_list", as: :mycancel_list, via: [:get, :post]
  match "mycart_list_by_buyer_id" => "myapis#mycart_list_by_buyer_id", as: :mycart_list_by_buyer_id, via: [:get, :post]
  match "mycart_list_by_cart_key" => "myapis#mycart_list_by_cart_key", as: :mycart_list_by_cart_key, via: [:get, :post]
  post 'add_to_cart_mobi' => 'myapis#add_to_cart_mobi', as: 'add_to_cart_mobi'
  post 'add_to_cart_mobi_with_key' => 'myapis#add_to_cart_mobi_with_key', as: 'add_to_cart_mobi_with_key'
  post 'delete_cart' => 'myapis#delete_cart', as: 'delete_cart'

  resources :cover_images
  scope "(:locale)", locale: /en|mm/ do
  resources :currency_exchanges
  resources :wish_lists
  resources :request_products
  get 'thanks_for_request' => 'request_products#thanks_for_request', as: 'thanks_for_request'

  devise_for :buyers, :controllers => {:sessions => "buyers/sessions", :registrations => "buyers/registrations"}

  namespace :myapi do
    namespace :v1 do
      devise_scope :buyer do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        post 'buyer_new' => 'registrations#buyer_new', :as => 'buyer_new'
        get 'my_sign_out' => 'sessions#destroy', :as => 'logout'
        
      end
    end
  end

  devise_for :admins, :controllers => {:sessions => "admins/sessions", :registrations => "admins/registrations"}
  resources :admins
  get 'dashboard' => 'admins#dashboard'
  get 'buyer_list' => 'admins#buyer_list'
  get 'other_request_products' => 'admins#other_request_products'  

  resources :comments
  resources :coupons
  resources :buyers
  resources :carts

  resources :line_items
  get 'cart_item' => 'line_items#cart_item', as: 'cart_item'

  resources :orders

   match "order_complete" => "orders#order_complete", as: :order_complete, via: [:get, :post]

  resources :frontends
  get 'submit_online_payment_mobi' => 'frontends#submit_online_payment_mobi'  

  root 'frontends#home'
 
  match 'fill_your_order_form/:id' => 'frontends#fill_your_order_form', as: 'fill_your_order_form', via: [:get, :post]
  get 'submit_online_payment' => 'frontends#submit_online_payment', as: 'submit_online_payment', via: [:get, :post]

  get 'order_form' => 'frontends#order_form', as: 'order_form'
  get 'about_us' => 'frontends#about_us'
  match 'contact_us' => 'frontends#contact_us', as: :contact_us, via: [:get, :post]
  get 'help' => 'frontends#help'
  get 'product_info/:id' => 'frontends#product_info', as: 'product_info'
  get 'view_image/:id' => 'frontends#view_image', as: 'view_image'

  get 'search_result' => 'frontends#search_result'

  
   get 'how_to_buy' => 'frontends#how_to_buy'
   get 'payment' => 'frontends#payment'
   get 'shipment_delivery'  => 'frontends#shipment_delivery'
   get 'customer_feedback'  => 'frontends#customer_feedback'

   get 'career_opportunity'  => 'frontends#career_opportunity'
   get 'termns_and_condition'  => 'frontends#termns_and_condition'
   get 'privacy_policy'  => 'frontends#privacy_policy'

   get 'my_account'  => 'frontends#my_account'

   get 'check_out'  => 'frontends#check_out'
   
   get 'use_coupon'  => 'frontends#use_coupon'
   post 'add_to_wish_list'  => 'frontends#add_to_wish_list'

  get 'product_detail_mobiview/:id'  => 'frontends#product_detail_mobiview'
  
  get 'customer_review_mobiview/:id'  => 'frontends#customer_review_mobiview'

  get 'productqanda_mobiview/:id'  => 'frontends#productqanda_mobiview'

  get 'notice_mobiview/:id'  => 'frontends#notice_mobiview'

  get 'my_wishlist'  => 'frontends#my_wishlist'

  get 'my_coupon'  => 'frontends#my_coupon'

  get 'send_to_order'  => 'frontends#send_to_order'

  get 'use_mpu' => 'frontends#use_mpu'

  get 'use_cash_deposit' => 'frontends#use_cash_deposit'

  get 'use_bank_transfer' => 'frontends#use_bank_transfer'

  get 'my_order_list' => 'frontends#my_order_list'

  get 'my_shopping_list' => 'frontends#my_shopping_list'

  get 'my_order_detail/:id' => 'frontends#my_order_detail', as: 'my_order_detail'
  

  get 'cancel_order/:id' => 'frontends#cancel_order', as: 'cancel_order'
  
  get 'my_cancel_list' => 'frontends#my_cancel_list'

  get 'my_personal_info/:id' => 'frontends#my_personal_info', as: 'my_personal_info'

  get 'product_list' => 'frontends#product_list', as: 'product_list'

  get 'pc_version' => 'frontends#pc_version', as: 'pc_version'

  get "send_to_pusher" => "frontends#send_to_pusher", :as => :send_to_pusher
  get 'chat_with' => 'frontends#chat_with', :as => :chat_with

  get 'chat_to_seller' => "frontends#chat_to_seller", :as => :chat_to_seller

  
  resources :products

      end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'Biyer'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'Buyer'

  has_many :messages, dependent: :destroy
  belongs_to :buyer

  # validates_uniqueness_of :sender_id, :scope => :recipient_id

  # scope :involving, -> (user) do
  #   where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  # end

  # scope :between, -> (sender_id,recipient_id) do
  #   where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  # end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_buyer!

  layout false

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id],params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end

    render json: { conversation_id: @conversation.id }
  end


  def my_conversation

  end

  def show
    @conversation = Conversation.find(params[:id])
    @reciever = interlocutor(@conversation)
    @messages = @conversation.messages
    @message = Message.new
  end

  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

  def interlocutor(conversation)
    current_user == conversation.recipient ? conversation.sender : conversation.recipient
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= form_for(@conversation) do |f| %>
  <% if @conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% @conversation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sender_id %><br>
    <%= f.number_field :sender_id %>
  </div>
  <div class="field">
    <%= f.label :recipient_id %><br>
    <%= f.number_field :recipient_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form' %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Conversations</h1>

<table>
  <thead>
    <tr>
      <th>Sender</th>
      <th>Recipient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |conversation| %>
      <tr>
        <td><%= conversation.sender_id %></td>
        <td><%= conversation.recipient_id %></td>
        <td><%= link_to 'Show', conversation %></td>
        <td><%= link_to 'Edit', edit_conversation_path(conversation) %></td>
        <td><%= link_to 'Destroy', conversation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conversation', new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form' %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
  <%= javascript_include_tag 'jquery_ujs.js' %>


<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>

    <h1><%= @reciever.name %> </h1>
  </div>
  <div class="chatboxoptions">
    <%= link_to "<i class='fa  fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='fa  fa-times'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<div class="chatboxinput">
  <%= form_for([@conversation, @message], :remote => true, :html => { id: "conversation_form_#{@conversation.id}"}) do |f| %>
      <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @conversation.id %>
  <% end %>
</div>

<%= subscribe_to conversation_path(@conversation) %>