config/routes.rb
Rails.application.routes.draw do

  resources :conversations do
    resources :messages
  end

  resources :myapis
  match "product_by_category" => "myapis#product_by_category", as: :product_by_category, via: [:get, :post]
  match "product_by_id" => "myapis#product_by_id", as: :product_by_id, via: [:get, :post]
  match "all_products" => "myapis#all_products", as: :all_products, via: [:get, :post]
  match "customer_review" => "myapis#customer_review", as: :customer_review, via: [:get, :post]
  match "my_info" => "myapis#my_info", as: :my_info, via: [:get, :post]
  match "edit_my_info" => "myapis#edit_my_info", as: :edit_my_info, via: [:get, :post]
  match "my_shoppinglist" => "myapis#my_shoppinglist", as: :my_shoppinglist, via: [:get, :post]
  match "my_wish_list" => "myapis#my_wish_list", as: :my_wish_list, via: [:get, :post]
  match "my_coupon_list" => "myapis#my_coupon_list", as: :my_coupon_list, via: [:get, :post]
  match "myorder_list" => "myapis#myorder_list", as: :myorder_list, via: [:get, :post]
  match "mycancel_list" => "myapis#mycancel_list", as: :mycancel_list, via: [:get, :post]
  match "mycart_list_by_buyer_id" => "myapis#mycart_list_by_buyer_id", as: :mycart_list_by_buyer_id, via: [:get, :post]
  match "mycart_list_by_cart_key" => "myapis#mycart_list_by_cart_key", as: :mycart_list_by_cart_key, via: [:get, :post]
  post 'add_to_cart_mobi' => 'myapis#add_to_cart_mobi', as: 'add_to_cart_mobi'
  post 'add_to_cart_mobi_with_key' => 'myapis#add_to_cart_mobi_with_key', as: 'add_to_cart_mobi_with_key'
  post 'delete_cart' => 'myapis#delete_cart', as: 'delete_cart'

  resources :cover_images
  scope "(:locale)", locale: /en|mm/ do
  resources :currency_exchanges
  resources :wish_lists
  resources :request_products
  get 'thanks_for_request' => 'request_products#thanks_for_request', as: 'thanks_for_request'

  devise_for :buyers, :controllers => {:sessions => "buyers/sessions", :registrations => "buyers/registrations"}

  namespace :myapi do
    namespace :v1 do
      devise_scope :buyer do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        post 'buyer_new' => 'registrations#buyer_new', :as => 'buyer_new'
        get 'my_sign_out' => 'sessions#destroy', :as => 'logout'
        
      end
    end
  end

  devise_for :admins, :controllers => {:sessions => "admins/sessions", :registrations => "admins/registrations"}
  resources :admins
  get 'dashboard' => 'admins#dashboard'
  get 'buyer_list' => 'admins#buyer_list'
  get 'other_request_products' => 'admins#other_request_products'  

  resources :comments
  resources :coupons
  resources :buyers
  resources :carts

  resources :line_items
  get 'cart_item' => 'line_items#cart_item', as: 'cart_item'

  resources :orders

   match "order_complete" => "orders#order_complete", as: :order_complete, via: [:get, :post]

  resources :frontends
  get 'submit_online_payment_mobi' => 'frontends#submit_online_payment_mobi'  

  root 'frontends#home'
 
  match 'fill_your_order_form/:id' => 'frontends#fill_your_order_form', as: 'fill_your_order_form', via: [:get, :post]
  get 'submit_online_payment' => 'frontends#submit_online_payment', as: 'submit_online_payment', via: [:get, :post]

  get 'order_form' => 'frontends#order_form', as: 'order_form'
  get 'about_us' => 'frontends#about_us'
  match 'contact_us' => 'frontends#contact_us', as: :contact_us, via: [:get, :post]
  get 'help' => 'frontends#help'
  get 'product_info/:id' => 'frontends#product_info', as: 'product_info'
  get 'view_image/:id' => 'frontends#view_image', as: 'view_image'

  get 'search_result' => 'frontends#search_result'

  
   get 'how_to_buy' => 'frontends#how_to_buy'
   get 'payment' => 'frontends#payment'
   get 'shipment_delivery'  => 'frontends#shipment_delivery'
   get 'customer_feedback'  => 'frontends#customer_feedback'

   get 'career_opportunity'  => 'frontends#career_opportunity'
   get 'termns_and_condition'  => 'frontends#termns_and_condition'
   get 'privacy_policy'  => 'frontends#privacy_policy'

   get 'my_account'  => 'frontends#my_account'

   get 'check_out'  => 'frontends#check_out'
   
   get 'use_coupon'  => 'frontends#use_coupon'
   post 'add_to_wish_list'  => 'frontends#add_to_wish_list'

  get 'product_detail_mobiview/:id'  => 'frontends#product_detail_mobiview'
  
  get 'customer_review_mobiview/:id'  => 'frontends#customer_review_mobiview'

  get 'productqanda_mobiview/:id'  => 'frontends#productqanda_mobiview'

  get 'notice_mobiview/:id'  => 'frontends#notice_mobiview'

  get 'my_wishlist'  => 'frontends#my_wishlist'

  get 'my_coupon'  => 'frontends#my_coupon'

  get 'send_to_order'  => 'frontends#send_to_order'

  get 'use_mpu' => 'frontends#use_mpu'

  get 'use_cash_deposit' => 'frontends#use_cash_deposit'

  get 'use_bank_transfer' => 'frontends#use_bank_transfer'

  get 'my_order_list' => 'frontends#my_order_list'

  get 'my_shopping_list' => 'frontends#my_shopping_list'

  get 'my_order_detail/:id' => 'frontends#my_order_detail', as: 'my_order_detail'
  

  get 'cancel_order/:id' => 'frontends#cancel_order', as: 'cancel_order'
  
  get 'my_cancel_list' => 'frontends#my_cancel_list'

  get 'my_personal_info/:id' => 'frontends#my_personal_info', as: 'my_personal_info'

  get 'product_list' => 'frontends#product_list', as: 'product_list'

  get 'pc_version' => 'frontends#pc_version', as: 'pc_version'

  get "send_to_pusher" => "frontends#send_to_pusher", :as => :send_to_pusher
  get 'chat_with' => 'frontends#chat_with', :as => :chat_with

  get 'chat_to_seller' => "frontends#chat_to_seller", :as => :chat_to_seller

  
  resources :products

      end
end

app/models/cart.rb
class Cart < ActiveRecord::Base

	has_many :line_items, :dependent => :destroy

	def add_item(product_id,size,color,delivery_method,quantity,product_model)
		current_item = line_items.where(:product_id => product_id).first
		# if current_item
		# 	current_item.quantity += 1
		# else
			current_item = LineItem.new(:product_id=> product_id,:product_size => size,:product_color => color,:delivery_method => delivery_method,:quantity => quantity.to_i, :product_model => product_model)
			line_items << current_item
		# end
		# current_item
	end


	def add_item_mobi(product_id,size,color,delivery_method,quantity,product_model,buyer_id)
		current_item = line_items.where(:product_id => product_id).first
		current_item = LineItem.new(:product_id=> product_id,:product_size => size,:product_color => color,:delivery_method => delivery_method,:quantity => quantity.to_i, :product_model => product_model, :buyer_id => buyer_id.to_i)
		line_items << current_item
	end


	def add_item_mobi_with_key(product_id,size,color,delivery_method,quantity,product_model,cart_key)
		current_item = line_items.where(:product_id => product_id).first
		# if current_item
		# 	current_item.quantity += 1
		# else
			current_item = LineItem.new(:product_id=> product_id,:product_size => size,:product_color => color,:delivery_method => delivery_method,:quantity => quantity.to_i, :product_model => product_model, :cart_key => cart_key)
			line_items << current_item
		# end
		# current_item
	end



	


	def total_price
		line_items.to_a.sum { |product| product.total_price }
	end

    def total_quantity
		line_items.to_a.sum { |product| product.quantity }
	end

	



end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end


  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to my_product_path, :notice => 'Invalid cart'
    else
      respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @cart }
      end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to my_products_path, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to my_products_path, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy

    @cart = Cart.find(params[:id])
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to(my_product_path, :notice => 'Your cart is currently empty') }
      format.xml { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="modal-content">
           <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
             <h4 class="modal-title">Shopping Cart</h4>
           </div>
           <div class="modal-body">
            	<table class="table table-striped">
		              <thead>
		                <tr>
		                  <th>Name</th>
		                  <th>Quantity</th>
		                  <th>Price</th>
		                  <th></th>
		                </tr>
		              </thead>
		              <tbody>
		              	<%= render(cart.line_items) %>
		                <tr>
		                  <th></th>
		                  <th>Total</th>
		                  <th><%= (cart.total_price) %> Ks</th>
		                  <th>&nbsp;</th>
		                </tr>
		              </tbody>
            	</table>
           </div>
           <div class="modal-footer">
     		 <%= link_to 'Empty cart', cart, :method => :delete, :confirm => 'Are you sure?', :class => "btn btn-danger" %>
             <button type="button" class="btn btn-default" data-dismiss="modal">Continue Shopping</button>
        		<%= link_to "Checkout", new_shipping_info_path, :class => "btn btn-info", :target => "_blank"  %>
           </div>
         </div><!-- /.modal-content -->

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>