config/routes.rb
Rails.application.routes.draw do

  resources :conversations do
    resources :messages
  end

  resources :myapis
  match "product_by_category" => "myapis#product_by_category", as: :product_by_category, via: [:get, :post]
  match "product_by_id" => "myapis#product_by_id", as: :product_by_id, via: [:get, :post]
  match "all_products" => "myapis#all_products", as: :all_products, via: [:get, :post]
  match "customer_review" => "myapis#customer_review", as: :customer_review, via: [:get, :post]
  match "my_info" => "myapis#my_info", as: :my_info, via: [:get, :post]
  match "edit_my_info" => "myapis#edit_my_info", as: :edit_my_info, via: [:get, :post]
  match "my_shoppinglist" => "myapis#my_shoppinglist", as: :my_shoppinglist, via: [:get, :post]
  match "my_wish_list" => "myapis#my_wish_list", as: :my_wish_list, via: [:get, :post]
  match "my_coupon_list" => "myapis#my_coupon_list", as: :my_coupon_list, via: [:get, :post]
  match "myorder_list" => "myapis#myorder_list", as: :myorder_list, via: [:get, :post]
  match "mycancel_list" => "myapis#mycancel_list", as: :mycancel_list, via: [:get, :post]
  match "mycart_list_by_buyer_id" => "myapis#mycart_list_by_buyer_id", as: :mycart_list_by_buyer_id, via: [:get, :post]
  match "mycart_list_by_cart_key" => "myapis#mycart_list_by_cart_key", as: :mycart_list_by_cart_key, via: [:get, :post]
  post 'add_to_cart_mobi' => 'myapis#add_to_cart_mobi', as: 'add_to_cart_mobi'
  post 'add_to_cart_mobi_with_key' => 'myapis#add_to_cart_mobi_with_key', as: 'add_to_cart_mobi_with_key'
  post 'delete_cart' => 'myapis#delete_cart', as: 'delete_cart'

  resources :cover_images
  scope "(:locale)", locale: /en|mm/ do
  resources :currency_exchanges
  resources :wish_lists
  resources :request_products
  get 'thanks_for_request' => 'request_products#thanks_for_request', as: 'thanks_for_request'

  devise_for :buyers, :controllers => {:sessions => "buyers/sessions", :registrations => "buyers/registrations"}

  namespace :myapi do
    namespace :v1 do
      devise_scope :buyer do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        post 'buyer_new' => 'registrations#buyer_new', :as => 'buyer_new'
        get 'my_sign_out' => 'sessions#destroy', :as => 'logout'
        
      end
    end
  end

  devise_for :admins, :controllers => {:sessions => "admins/sessions", :registrations => "admins/registrations"}
  resources :admins
  get 'dashboard' => 'admins#dashboard'
  get 'buyer_list' => 'admins#buyer_list'
  get 'other_request_products' => 'admins#other_request_products'  

  resources :comments
  resources :coupons
  resources :buyers
  resources :carts

  resources :line_items
  get 'cart_item' => 'line_items#cart_item', as: 'cart_item'

  resources :orders

   match "order_complete" => "orders#order_complete", as: :order_complete, via: [:get, :post]

  resources :frontends
  get 'submit_online_payment_mobi' => 'frontends#submit_online_payment_mobi'  

  root 'frontends#home'
 
  match 'fill_your_order_form/:id' => 'frontends#fill_your_order_form', as: 'fill_your_order_form', via: [:get, :post]
  get 'submit_online_payment' => 'frontends#submit_online_payment', as: 'submit_online_payment', via: [:get, :post]

  get 'order_form' => 'frontends#order_form', as: 'order_form'
  get 'about_us' => 'frontends#about_us'
  match 'contact_us' => 'frontends#contact_us', as: :contact_us, via: [:get, :post]
  get 'help' => 'frontends#help'
  get 'product_info/:id' => 'frontends#product_info', as: 'product_info'
  get 'view_image/:id' => 'frontends#view_image', as: 'view_image'

  get 'search_result' => 'frontends#search_result'

  
   get 'how_to_buy' => 'frontends#how_to_buy'
   get 'payment' => 'frontends#payment'
   get 'shipment_delivery'  => 'frontends#shipment_delivery'
   get 'customer_feedback'  => 'frontends#customer_feedback'

   get 'career_opportunity'  => 'frontends#career_opportunity'
   get 'termns_and_condition'  => 'frontends#termns_and_condition'
   get 'privacy_policy'  => 'frontends#privacy_policy'

   get 'my_account'  => 'frontends#my_account'

   get 'check_out'  => 'frontends#check_out'
   
   get 'use_coupon'  => 'frontends#use_coupon'
   post 'add_to_wish_list'  => 'frontends#add_to_wish_list'

  get 'product_detail_mobiview/:id'  => 'frontends#product_detail_mobiview'
  
  get 'customer_review_mobiview/:id'  => 'frontends#customer_review_mobiview'

  get 'productqanda_mobiview/:id'  => 'frontends#productqanda_mobiview'

  get 'notice_mobiview/:id'  => 'frontends#notice_mobiview'

  get 'my_wishlist'  => 'frontends#my_wishlist'

  get 'my_coupon'  => 'frontends#my_coupon'

  get 'send_to_order'  => 'frontends#send_to_order'

  get 'use_mpu' => 'frontends#use_mpu'

  get 'use_cash_deposit' => 'frontends#use_cash_deposit'

  get 'use_bank_transfer' => 'frontends#use_bank_transfer'

  get 'my_order_list' => 'frontends#my_order_list'

  get 'my_shopping_list' => 'frontends#my_shopping_list'

  get 'my_order_detail/:id' => 'frontends#my_order_detail', as: 'my_order_detail'
  

  get 'cancel_order/:id' => 'frontends#cancel_order', as: 'cancel_order'
  
  get 'my_cancel_list' => 'frontends#my_cancel_list'

  get 'my_personal_info/:id' => 'frontends#my_personal_info', as: 'my_personal_info'

  get 'product_list' => 'frontends#product_list', as: 'product_list'

  get 'pc_version' => 'frontends#pc_version', as: 'pc_version'

  get "send_to_pusher" => "frontends#send_to_pusher", :as => :send_to_pusher
  get 'chat_with' => 'frontends#chat_with', :as => :chat_with

  get 'chat_to_seller' => "frontends#chat_to_seller", :as => :chat_to_seller

  
  resources :products

      end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

	belongs_to :product
	belongs_to :cart




		 # def total_price

		 # 	@currency_exchange = CurrencyExchange.pluck(:currency_rate).last
	 	# 	number = product.discount_price.to_i * @currency_exchange.to_i
		 #    last_three_number = (number.to_s).last(3).to_s
		 #    mylast_fourth_number = (number.to_s).last(4).to_s
		 #    fourth_number = (number.to_s).last(4).to_s.first

	
		    
		 #    if 500 <= last_three_number.to_i

		    
		 #      last_fourth_number = fourth_number.to_i+1
		 #      fourth_number = last_fourth_number.to_s+"000"
		 #      product_price = (number.to_s).gsub(mylast_fourth_number,fourth_number)

		 #      product_price.to_i * quantity 

		   

		 #    elsif 500 > last_three_number.to_i

		 #      last_fourth_number = fourth_number.to_i
		 #      fourth_number = last_fourth_number.to_s+"000"
		 #      product_price = (number.to_s).gsub(mylast_fourth_number,fourth_number)
		  
		 #      product_price.to_i * quantity


		 #    else
		 #    end
		   
    
   #      end


        def total_price

	          @currency_exchange = CurrencyExchange.pluck(:currency_rate).last
		 	  number = product.discount_price.to_i * @currency_exchange.to_i
			  length = (number.to_s).length
			  my_length = length-3
			  first_three_number = (number.to_s).first(my_length).to_s
			  last_three_number = (number.to_s).last(3).to_s


			      if 500 <= last_three_number.to_i

			        myfirst_three_number = first_three_number.to_i+1
			        product_price = myfirst_three_number.to_s+"000"
			        product_price.to_i * quantity 

			      elsif 500 > last_three_number.to_i


			          myfirst_three_number = first_three_number.to_i
			          product_price = myfirst_three_number.to_s+"000"
			          product_price.to_i * quantity 

			      end




        end

	





end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json

  def round_up(number)




length = (number.to_s).length
my_length = length-3
  first_three_number = (number.to_s).first(my_length).to_s
  last_three_number = (number.to_s).last(3).to_s


      if 500 <= last_three_number.to_i

        myfirst_three_number = first_three_number.to_i+1
        $product_price = myfirst_three_number.to_s+"000"

      elsif 500 > last_three_number.to_i


          myfirst_three_number = first_three_number.to_i
          $product_price = myfirst_three_number.to_s+"000"

      end

   
    
  end

  def create
      @cart = current_cart
      puts "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"+@cart.to_s+"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
      
      product = Product.find(params[:product_id])
      color = params[:product_color]
      delivery_method = params[:delivery_method]
      size = params[:product_size]
      quantity = params[:product_quantity].to_i
      product_model = params[:product_model]

      @line_item = @cart.add_item(product.id,size,color,delivery_method,quantity,product_model)
      respond_to do |format|
            if @line_item.save
              format.html { redirect_to request.referer }
              format.xml { render :xml => @line_item, :status => :created, :location => @line_item }
            else
              format.html { render :action => "new" }
              format.xml { render :xml => @line_item.errors, :status => :unprocessable_entity }
            end
        end
   end





  def cart_item
      
      @coupons = Coupon.all


      if params[:cart_id]
         @line_items = LineItem.where("cart_id = ? ", params[:cart_id])
      end

      if params[:buyer_id]
         @line_items = LineItem.where("buyer_id = ? ", params[:buyer_id])
      end



  end

   




  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to request.referer, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:cart_key, :product_model,:product_id, :cart_id, :buyer_id, :quantity, :product_size, :product_color, :delivery_method)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.number_field :cart_id %>
  </div>
  <div class="field">
    <%= f.label :buyer_id %><br>
    <%= f.number_field :buyer_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/cart_item.html.erb
<script src="http://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" />


<div class="container"> 

<h4 style="text-align:center;"> 

  <%= t("eBuy_checkout_list")%>


 </h4>
<br/>
<br/>
  <table class="table">
          <% @line_items.each do |line_item| %>
                      <tr>
                        <td style="width:30%;">
                          <a href="#">
                            <%= image_tag line_item.product.avatar1.url(:medium), :class => "img-thumbnail img-responsive" %>
                          </a>
                        </td>
                        <td >
                          <a href="#">
                            <%= line_item.product.short_title %><br/>

                            <span style="color:black;"><%= t("Product_Size")%>: </span><%= line_item.product_size %><br/>
                            <span style="color:black;"><%= t("Product_Color")%>: </span><%= line_item.product_color %><br/>
                            <span style="color:black;"><%= t("Product_Model")%>: </span> <%= line_item.product_model %><br/>

                          </a>
                        </td>
                        <td >
                        <% round_up(line_item.product.discount_price.to_i * @currency_exchange.to_i)  %>
                              <%= $product_price %> x <%= line_item.quantity %>
                        </td>
                        <td >
                          <%= line_item.total_price.to_i  %> Ks
                        </td>
                         <td >
                          <%= line_item.delivery_method  %>
                        </td>

                        <td ><%= link_to 'remove',line_item, method: :delete, data: { confirm: 'Are you sure?' } ,:class=>"btn btn-danger" %></td>
                      </tr>
         <% end %> 




  </table>
  <hr/>
  <br/>



  <form class="new_order" id="new_order" action="/submit_online_payment" >


      <div class="col-md-6">
  
        <h4>   <%= t("Personal_Information")%> </h4><hr>
      <div class="field">
        <p> <%= t("name") %></p>
        <input class="form-control" type="text" name="customer_name" id="customer_name">
       
      </div><br>
      <div class="field">
        <p><%= t("email") %></p>
        <input class="form-control" type="text" name="customer_email" id="customer_email">
      </div><br>
     
     



  

   </div>

   <div class="col-md-6">
  
        <h4><%= t("shipping_delivery") %></h4><hr>
      <div class="field">
         <p><%= t("phone") %></p>
         <input class="form-control" type="text" name="customer_phone" id="customer_phone">
      </div><br>
     
      <div class="field">
        <p><%= t("House_Number_Street") %></p>
         <input class="form-control" type="text" name="customer_house" id="customer_house">
      </div><br>

       <div class="field">
        <p><%= t("Township") %></p>
        <input class="form-control" type="text" name="customer_township" id="customer_township">
      </div><br>


       <div class="field">
        <p><%= t("City") %></p>
        <input class="form-control" type="text" name="customer_city" id="customer_city">
      </div><br>

     
   </div>





   <div class="col-md-12">
  <br/><br/>
    <%= t("Total_Price") %>: <%= (@cart.total_price) %> Ks
    <input type="button" id="opener" class="btn btn-small" value="Get Coupons"> 
    <br/> <br/>

    <%= t("Coupon_Code") %>:
    <input id="coupon_code"   >
      <input type="button" id="send_coupon" class="btn btn-default" value="Use"> 
    <br/> <br/>
      <%= t("Final Price") %>:
    <input id="total_price" name="total_price" placeholder="checkout_price">


     <input id="cart_id" name="cart_id" value="<%= params[:cart_id] %>" style="display:none;">

    <br/> <br/>
    <input type="submit" name="commit" value="Submit Payment" class="btn btn-primary btn-lg btn-block">
  </div>
  <br/>
</form>

</div>


  <br/>
  <br/>



<!-- coupon dialog -->



<div id="dialog1" title="Coupon list" hidden="hidden" style="width:900px;">


   <table class="table table-hover">
      <thead>
        <tr>
          <th> <%= t("Coupon") %></th>
          <th> <%= t("Percentage") %></th>
          <th> <%= t("Limit") %></th>
          <th> <%= t("Expire_on") %></th>
          <th> <%= t("Action") %></th>
        </tr>
      </thead>
      <tbody>
        <% @coupons.each do |coupon| %>
          <tr>
            <td><%= coupon.title %></td>
            <td><%= coupon.discount_percentage %></td>
            <td><%= coupon.limitation %></td>
            <td><%= coupon.expire_date %></td>
            <td> 
            <button id="apply_co" value="<%= coupon.title %>" onClick='reply_click(this)'> Add</button>
            </td>
          </tr>
        <% end %>
      </tbody>

    </table>


 


</div>



 <script>

    $(function () {
      $( "#dialog1" ).dialog({
         resizable: false,
         autoOpen: false,
         width: 'auto'

      });
      
      $("#opener").click(function() {
        $("#dialog1").dialog('open');
      });
    });

  </script>


<script type="text/javascript">

    function reply_click(objButton)
    {
        var code = objButton.value;
        document.getElementById("coupon_code").value = code;
    }

</script>


<script type="text/javascript">
  
 $('#send_coupon').click(function() {
 

    coupon_code = document.getElementById("coupon_code").value;
    limitation = "<%= @cart.total_price  %>";


      $.ajax({
              type: 'get',
              url: 'use_coupon',
              dataType: 'text',
              data: {'title':coupon_code, 'limitation':limitation},
              complete: function(r){
              
                  raw_discount_price = r.responseText;
                  clean_discount_price = raw_discount_price.replace('{:discount_price=>["', "");
                  discount_percent = clean_discount_price.replace('"]}', "");
                 
                  // couopon calculation
                  var percentage = parseFloat(discount_percent/100);
                  var descrease_amount =  parseInt(percentage*limitation);
                  var actual_amount = parseInt(limitation-descrease_amount);

                  if (raw_discount_price == "{:discount_price=>[]}"){
                  
                    document.getElementById("total_price").value = " <%= @cart.total_price %>"


                  } else {

                    document.getElementById("total_price").value = actual_amount;
                    
                  }
                  
         



              }
           });






    });


</script>




<script type="text/javascript">
  
$(document).ready(function(){ 

  document.getElementById("total_price").value = "<%= @cart.total_price %>";


    "<% if buyer_signed_in? %>"

     document.getElementById("customer_name").value = "<%= current_buyer.buyer_name %>";
     document.getElementById("customer_email").value = "<%= current_buyer.email %>";
     document.getElementById("customer_phone").value = "<%= current_buyer.buyer_phone %>";
     document.getElementById("customer_house").value = "<%= current_buyer.buyer_address %>";
     document.getElementById("customer_township").value = "<%= current_buyer.buyer_township %>";
     document.getElementById("customer_city").value = "Yangon";


  "<% end %>"

});

</script>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th>Buyer</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= line_item.buyer_id %></td>
        <td><%= line_item.quantity %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<p>
  <strong>Buyer:</strong>
  <%= @line_item.buyer_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @line_item.quantity %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>